export type ResponseMode = "standard" | "speed" | "thinking" | "expert" | "mirror" | "growth" | "quantum-lens" | "deep-search";
export type EvidenceLabel = "factual" | "inferred" | "speculative" | "symbolic" | "uncertain";
export type GoalStatus = "open" | "active" | "paused" | "achieved" | "abandoned";
export type GoalMilestoneStatus = "pending" | "in_progress" | "completed";
export type NotificationFrequency = "daily" | "every_2_days" | "weekly";
export type NotificationTone = "motivational" | "reflective" | "mixed";
export type MemorySourceType = "journal" | "diary" | "note" | "goal" | "analysis" | "manual";
export interface NavigationItem {
    href: string;
    label: string;
    description: string;
}
export interface PolicyDefinition {
    id: string;
    title: string;
    description: string;
    enforcementMode: "log" | "warn" | "block" | "halt";
    active: boolean;
}
export interface JournalEntrySummary {
    id: string;
    title: string;
    type: "journal" | "diary" | "note";
    createdAt: string;
    mood?: string;
}
export interface DiaryEntrySummary {
    id: string;
    title: string;
    content: string;
    mood: string;
    entryDate: string;
    autoGenerated: boolean;
    sourceContext?: string;
    createdAt: string;
    updatedAt: string;
}
export interface NoteSummary {
    id: string;
    title: string;
    content: string;
    category: string;
    tags: string[];
    isPinned: boolean;
    updatedAt: string;
}
export interface GoalMilestone {
    id: string;
    title: string;
    status: GoalMilestoneStatus;
    dueDate?: string;
    completedAt?: string;
}
export interface GoalSummary {
    id: string;
    title: string;
    description: string;
    lifeArea: string;
    status: GoalStatus;
    progressPercent: number;
    dueDate?: string;
    milestones: GoalMilestone[];
    updatedAt: string;
}
export interface NotificationPreference {
    developmentEnabled: boolean;
    goalRemindersEnabled: boolean;
    frequency: NotificationFrequency;
    preferredTime: string;
    preferredWeekday: string;
    tone: NotificationTone;
}
export interface NotificationHistoryItem {
    id: string;
    notificationType: "growth" | "goal" | "security";
    channel: "email" | "in-app";
    title: string;
    message: string;
    deliveredAt: string;
    status: "queued" | "sent" | "failed";
}
export interface AnalysisInput {
    title?: string;
    content: string;
    context?: string[];
}
export interface AnalysisReport {
    id: string;
    mode: ResponseMode;
    evidenceLabel: EvidenceLabel;
    summary: string;
    observation: string;
    psychology: string;
    archetype: string;
    shadowCheck: string;
    developmentHint: string;
    timelineConnection: string;
    extractedConcepts: string[];
    suggestedQuestions: string[];
    generatedAt: string;
}
export interface MirrorReport extends AnalysisReport {
    disconfirmingView: string;
    mirrorQuestion: string;
}
export interface QuantumLensReport extends AnalysisReport {
    stateDescription: string;
    collapsePattern: string;
    hiddenOption: string;
    fieldQuestion: string;
}
export interface GrowthState {
    id: string;
    currentStage: string;
    focusArea: string;
    momentumScore: number;
    coherenceScore: number;
    strengths: string[];
    risks: string[];
    nextStep: string;
    updatedAt: string;
}
export interface GrowthIntervention {
    id: string;
    title: string;
    rationale: string;
    action: string;
    tone: NotificationTone;
    createdAt: string;
}
export interface MemoryItem {
    id: string;
    sourceType: MemorySourceType;
    title: string;
    content: string;
    concepts: string[];
    relevance: number;
    createdAt: string;
}
export interface MemorySearchResult {
    query: string;
    items: MemoryItem[];
    total: number;
    generatedAt: string;
}
