import { IsBoolean, IsDateString, IsNotEmpty, IsOptional, IsString } from "class-validator";

export class CreateDiaryEntryDto {
  @IsString()
  @IsNotEmpty()
  title!: string;

  @IsString()
  @IsNotEmpty()
  content!: string;

  @IsString()
  @IsNotEmpty()
  mood!: string;

  @IsDateString()
  entryDate!: string;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;

  @IsOptional()
  @IsString()
  sourceContext?: string;
}