import { IsBoolean, IsDateString, IsOptional, IsString } from "class-validator";

export class UpdateDiaryEntryDto {
  @IsOptional()
  @IsString()
  title?: string;

  @IsOptional()
  @IsString()
  content?: string;

  @IsOptional()
  @IsString()
  mood?: string;

  @IsOptional()
  @IsDateString()
  entryDate?: string;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;

  @IsOptional()
  @IsString()
  sourceContext?: string;
}