"use client";

import { FormEvent, useEffect, useState } from "react";
import type { DiaryEntrySummary, DiaryPromptRecord } from "@aion/shared-types";
import { apiRequest } from "../../lib/api";
import { StatusNotice } from "./status-notice";

const initialForm = {
  title: "",
  content: "",
  mood: "centered",
  entryDate: new Date().toISOString().slice(0, 10)
};

interface PreparedSummary {
  generatedAt: string;
  promptSeed: string[];
  latestEntryTitle: string | null;
}

export function DiaryWorkspace() {
  const [entries, setEntries] = useState<DiaryEntrySummary[]>([]);
  const [prompts, setPrompts] = useState<DiaryPromptRecord[]>([]);
  const [summary, setSummary] = useState<PreparedSummary | null>(null);
  const [form, setForm] = useState(initialForm);
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isPreparingSummary, setIsPreparingSummary] = useState(false);

  async function loadDiaryData() {
    setIsLoading(true);
    const [entriesResult, promptsResult] = await Promise.all([
      apiRequest<DiaryEntrySummary[]>("/diary"),
      apiRequest<DiaryPromptRecord[]>("/diary/prompts")
    ]);

    const failures: string[] = [];

    if (entriesResult.ok && entriesResult.data) {
      setEntries(entriesResult.data);
    } else {
      failures.push(entriesResult.error ?? "Tagebucheintraege konnten nicht geladen werden.");
    }

    if (promptsResult.ok && promptsResult.data) {
      setPrompts(promptsResult.data);
    } else {
      failures.push(promptsResult.error ?? "Tagebuchimpulse konnten nicht geladen werden.");
    }

    setError(failures.length > 0 ? failures.join(" ") : null);
    setStatus(failures.length === 0 ? "Das Tagebuch ist live mit API-Daten verbunden." : null);
    setIsLoading(false);
  }

  useEffect(() => {
    void loadDiaryData();
  }, []);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsSubmitting(true);
    setError(null);
    setStatus(null);

    const result = await apiRequest<DiaryEntrySummary>("/diary", {
      method: "POST",
      body: JSON.stringify({
        ...form,
        entryDate: new Date(form.entryDate).toISOString(),
        autoGenerated: false,
        sourceContext: "manual"
      })
    });

    if (result.ok && result.data) {
      setEntries((current) => [result.data as DiaryEntrySummary, ...current]);
      setForm(initialForm);
      setStatus("Tagebucheintrag wurde gespeichert.");
    } else {
      setError(result.error ?? "Tagebucheintrag konnte nicht gespeichert werden.");
    }

    setIsSubmitting(false);
  }

  async function prepareSummary() {
    setIsPreparingSummary(true);
    setError(null);

    const result = await apiRequest<PreparedSummary>("/diary/summary");
    if (result.ok && result.data) {
      setSummary(result.data);
      setStatus("Tageszusammenfassung wurde vorbereitet.");
    } else {
      setError(result.error ?? "Tageszusammenfassung konnte nicht vorbereitet werden.");
    }

    setIsPreparingSummary(false);
  }

  return (
    <div className="grid gap-6 xl:grid-cols-[1fr_0.95fr]">
      <article className="rounded-[28px] bg-white p-8 shadow-panel">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="font-body text-xs uppercase tracking-[0.28em] text-moss">Tagesreflexion</p>
            <h2 className="mt-2 font-display text-3xl text-ink">Gefuehrte Tagesansicht</h2>
          </div>
          <button
            type="button"
            onClick={prepareSummary}
            disabled={isPreparingSummary}
            className="rounded-2xl border border-moss/20 bg-moss/5 px-4 py-2 text-sm text-slate disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isPreparingSummary ? "Bereitet vor..." : "Tageszusammenfassung vorbereiten"}
          </button>
        </div>
        <div className="mt-6 space-y-3">
          {status ? <StatusNotice message={status} variant="success" /> : null}
          {error ? <StatusNotice message={error} variant="error" /> : null}
          {isLoading ? <StatusNotice message="Tagebuchdaten werden geladen..." /> : null}
        </div>
        <div className="mt-6 grid gap-3 md:grid-cols-3">
          {prompts.length === 0 && !isLoading ? <StatusNotice message="Noch keine Tagebuchimpulse vorhanden." /> : null}
          {prompts.map((prompt) => (
            <div key={prompt.id} className="rounded-2xl border border-mist bg-mist/35 p-4">
              <div className="text-xs uppercase tracking-[0.22em] text-moss">{prompt.promptType}</div>
              <p className="mt-3 text-sm leading-6 text-slate/80">{prompt.promptText}</p>
            </div>
          ))}
        </div>
        {summary ? (
          <div className="mt-6 rounded-3xl bg-slate p-5 text-mist">
            <div className="text-xs uppercase tracking-[0.22em] text-mist/60">Vorbereitete Zusammenfassung</div>
            <p className="mt-3 text-sm leading-7 text-mist/80">Letzter Fokus: {summary.latestEntryTitle ?? "noch kein Eintrag"}</p>
            <p className="mt-2 text-xs text-mist/60">Generiert: {new Date(summary.generatedAt).toLocaleString("de-DE")}</p>
          </div>
        ) : null}
      </article>
      <form onSubmit={handleSubmit} className="rounded-[28px] bg-white p-8 shadow-panel">
        <p className="font-body text-xs uppercase tracking-[0.28em] text-moss">Erfassung</p>
        <h2 className="mt-2 font-display text-3xl text-ink">Neuer Tagebucheintrag</h2>
        <div className="mt-6 grid gap-4">
          <input className="rounded-2xl border border-mist bg-mist/50 px-4 py-3 text-sm outline-none focus:border-moss" placeholder="Titel" value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} required />
          <div className="grid gap-4 md:grid-cols-2">
            <input className="rounded-2xl border border-mist bg-mist/50 px-4 py-3 text-sm outline-none focus:border-moss" type="date" value={form.entryDate} onChange={(event) => setForm((current) => ({ ...current, entryDate: event.target.value }))} required />
            <input className="rounded-2xl border border-mist bg-mist/50 px-4 py-3 text-sm outline-none focus:border-moss" placeholder="Stimmung" value={form.mood} onChange={(event) => setForm((current) => ({ ...current, mood: event.target.value }))} required />
          </div>
          <textarea className="min-h-40 rounded-3xl border border-mist bg-mist/50 px-4 py-4 text-sm leading-7 outline-none focus:border-moss" placeholder="Was hat den Tag getragen?" value={form.content} onChange={(event) => setForm((current) => ({ ...current, content: event.target.value }))} required />
          <button type="submit" disabled={isSubmitting} className="rounded-2xl bg-slate px-5 py-3 text-sm font-semibold text-mist transition hover:bg-ink disabled:cursor-not-allowed disabled:opacity-60">{isSubmitting ? "Speichert..." : "Tagebuch speichern"}</button>
        </div>
      </form>
      <article className="rounded-[28px] bg-white p-8 shadow-panel xl:col-span-2">
        <p className="font-body text-xs uppercase tracking-[0.28em] text-moss">Zeitverlauf</p>
        <div className="mt-6 grid gap-4 lg:grid-cols-2">
          {!isLoading && entries.length === 0 ? <StatusNotice message="Noch keine Tagebucheintraege vorhanden." /> : null}
          {entries.map((entry) => (
            <div key={entry.id} className="rounded-3xl border border-mist bg-mist/35 p-5">
              <div className="flex items-center justify-between gap-4">
                <h3 className="text-lg font-semibold text-ink">{entry.title}</h3>
                <span className="text-xs text-slate/60">{new Date(entry.entryDate).toLocaleDateString("de-DE")}</span>
              </div>
              <p className="mt-3 text-sm leading-7 text-slate/80">{entry.content}</p>
              <div className="mt-4 text-xs text-moss">Stimmung: {entry.mood}</div>
            </div>
          ))}
        </div>
      </article>
    </div>
  );
}
