import { Injectable, NotFoundException, OnModuleInit, Optional } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { DiaryEntrySummary } from "@aion/shared-types";
import { LOCAL_USER_ID } from "../common/app-constants";
import { PrismaService } from "../common/prisma.service";
import { AuditService } from "../audit/audit.service";
import { CreateDiaryEntryDto } from "./dto/create-diary-entry.dto";
import { UpdateDiaryEntryDto } from "./dto/update-diary-entry.dto";

interface DiaryPromptRecord {
  id: string;
  promptText: string;
  promptType: string;
}

interface DiaryEntryRecord extends DiaryEntrySummary {}

function createDefaultPrompts(): DiaryPromptRecord[] {
  return [
    {
      id: randomUUID(),
      promptType: "reflection",
      promptText: "Was war heute der ehrlichste Moment?"
    },
    {
      id: randomUUID(),
      promptType: "coherence",
      promptText: "Wo warst du heute koharent und wo nicht?"
    },
    {
      id: randomUUID(),
      promptType: "action",
      promptText: "Welcher kleine Schritt waere morgen wirklich echt?"
    }
  ];
}

function createDefaultEntries(): DiaryEntryRecord[] {
  const now = new Date().toISOString();

  return [
    {
      id: randomUUID(),
      title: "Tageszusammenfassung",
      content: "Heute war der Fokus klarer als gestern. Das System sollte daraus Wachstumsimpulse ableiten koennen.",
      mood: "focused",
      entryDate: now,
      autoGenerated: false,
      sourceContext: "manual",
      createdAt: now,
      updatedAt: now
    }
  ];
}

@Injectable()
export class DiaryService implements OnModuleInit {
  private prompts: DiaryPromptRecord[] = createDefaultPrompts();
  private entries: DiaryEntryRecord[] = createDefaultEntries();

  constructor(
    private readonly auditService: AuditService,
    @Optional() private readonly prisma?: PrismaService
  ) {}

  async onModuleInit() {
    if (!this.prisma) {
      return;
    }

    await this.prisma.ensureLocalUser();
    const [prompts, entries] = await Promise.all([
      this.prisma.diaryPrompt.findMany({ orderBy: { createdAt: "asc" } }),
      this.prisma.diaryEntry.findMany({
        where: { userId: LOCAL_USER_ID },
        orderBy: { createdAt: "desc" }
      })
    ]);

    if (prompts.length === 0) {
      await this.prisma.diaryPrompt.createMany({
        data: this.prompts.map((prompt) => ({
          id: prompt.id,
          promptText: prompt.promptText,
          promptType: prompt.promptType
        }))
      });
    } else {
      this.prompts = prompts.map((prompt) => ({
        id: prompt.id,
        promptText: prompt.promptText,
        promptType: prompt.promptType
      }));
    }

    if (entries.length === 0) {
      await this.prisma.diaryEntry.createMany({
        data: this.entries.map((entry) => ({
          id: entry.id,
          userId: LOCAL_USER_ID,
          title: entry.title,
          content: entry.content,
          mood: entry.mood,
          entryDate: new Date(entry.entryDate),
          autoGenerated: entry.autoGenerated,
          sourceContext: entry.sourceContext,
          createdAt: new Date(entry.createdAt),
          updatedAt: new Date(entry.updatedAt)
        }))
      });
    } else {
      this.entries = entries.map((entry) => ({
        id: entry.id,
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: entry.entryDate.toISOString(),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext ?? undefined,
        createdAt: entry.createdAt.toISOString(),
        updatedAt: entry.updatedAt.toISOString()
      }));
    }
  }

  private async persistCreate(entry: DiaryEntryRecord) {
    if (!this.prisma) {
      return;
    }

    await this.prisma.diaryEntry.create({
      data: {
        id: entry.id,
        userId: LOCAL_USER_ID,
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: new Date(entry.entryDate),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext,
        createdAt: new Date(entry.createdAt),
        updatedAt: new Date(entry.updatedAt)
      }
    });
  }

  private async persistUpdate(entry: DiaryEntryRecord) {
    if (!this.prisma) {
      return;
    }

    await this.prisma.diaryEntry.update({
      where: { id: entry.id },
      data: {
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: new Date(entry.entryDate),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext,
        updatedAt: new Date(entry.updatedAt)
      }
    });
  }

  private async persistDelete(id: string) {
    if (!this.prisma) {
      return;
    }

    await this.prisma.diaryEntry.delete({
      where: { id }
    });
  }

  listEntries() {
    return this.entries;
  }

  getEntry(id: string) {
    const entry = this.entries.find((item) => item.id === id);
    if (!entry) {
      throw new NotFoundException("Tagebucheintrag nicht gefunden.");
    }

    return entry;
  }

  getPrompts() {
    return this.prompts;
  }

  async createEntry(dto: CreateDiaryEntryDto) {
    const now = new Date().toISOString();
    const entry: DiaryEntryRecord = {
      id: randomUUID(),
      createdAt: now,
      updatedAt: now,
      autoGenerated: dto.autoGenerated ?? false,
      sourceContext: dto.sourceContext,
      title: dto.title,
      content: dto.content,
      mood: dto.mood,
      entryDate: dto.entryDate
    };

    this.entries.unshift(entry);
    await this.persistCreate(entry);
    await this.auditService.record({
      category: "diary",
      action: "entry.created",
      resource: entry.id,
      actorType: "user",
      actorId: LOCAL_USER_ID,
      detail: `Der Tagebucheintrag "${entry.title}" wurde angelegt.`
    });
    return entry;
  }

  async updateEntry(id: string, dto: UpdateDiaryEntryDto) {
    const entry = this.getEntry(id);
    Object.assign(entry, dto, { updatedAt: new Date().toISOString() });
    await this.persistUpdate(entry);
    await this.auditService.record({
      category: "diary",
      action: "entry.updated",
      resource: entry.id,
      actorType: "user",
      actorId: LOCAL_USER_ID,
      detail: `Der Tagebucheintrag "${entry.title}" wurde aktualisiert.`
    });
    return entry;
  }

  async removeEntry(id: string) {
    const index = this.entries.findIndex((item) => item.id === id);
    if (index === -1) {
      throw new NotFoundException("Tagebucheintrag nicht gefunden.");
    }

    const [removed] = this.entries.splice(index, 1);
    await this.persistDelete(id);
    await this.auditService.record({
      category: "diary",
      action: "entry.removed",
      resource: removed.id,
      actorType: "user",
      actorId: LOCAL_USER_ID,
      detail: `Der Tagebucheintrag "${removed.title}" wurde entfernt.`
    });
    return removed;
  }

  prepareDailySummary() {
    const latest = this.entries[0];
    return {
      generatedAt: new Date().toISOString(),
      promptSeed: this.prompts.map((prompt) => prompt.promptText),
      latestEntryTitle: latest?.title ?? null
    };
  }
}
