import { expect, test } from "@playwright/test";

test("dashboard renders live counts from intercepted API responses", async ({ page }) => {
  await page.route("http://localhost:4000/**", async (route) => {
    const url = new URL(route.request().url());

    switch (url.pathname) {
      case "/journal":
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify([
            {
              id: "journal-1",
              title: "Entry 1",
              content: "Reflection",
              entryType: "journal",
              createdAt: "2026-03-08T08:00:00.000Z",
              updatedAt: "2026-03-08T08:00:00.000Z"
            },
            {
              id: "journal-2",
              title: "Entry 2",
              content: "Reflection",
              entryType: "journal",
              createdAt: "2026-03-08T09:00:00.000Z",
              updatedAt: "2026-03-08T09:00:00.000Z"
            }
          ])
        });
        return;
      case "/diary":
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify([
            {
              id: "diary-1",
              title: "Morning",
              content: "Check-in",
              mood: "steady",
              entryDate: "2026-03-08",
              autoGenerated: false,
              createdAt: "2026-03-08T07:00:00.000Z",
              updatedAt: "2026-03-08T07:00:00.000Z"
            }
          ])
        });
        return;
      case "/notes":
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify([
            {
              id: "note-1",
              title: "Idea",
              content: "Hook up memory",
              category: "Ideas",
              tags: ["memory"],
              isPinned: true,
              updatedAt: "2026-03-08T06:00:00.000Z"
            }
          ])
        });
        return;
      case "/goals":
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            items: [],
            stats: {
              total: 1,
              active: 1,
              completed: 0,
              averageProgress: 64,
              completionRate: 0
            }
          })
        });
        return;
      default:
        await route.fulfill({
          status: 404,
          contentType: "application/json",
          body: JSON.stringify({ message: `Unhandled route: ${url.pathname}` })
        });
    }
  });

  await page.goto("/dashboard");

  await expect(page.getByText("Dashboard zeigt Live-Zahlen aus der API.")).toBeVisible();
  await expect(page.locator('a[href="/journal"]').nth(1)).toContainText("2");
  await expect(page.locator('a[href="/diary"]').nth(1)).toContainText("1");
  await expect(page.locator('a[href="/notes"]').nth(1)).toContainText("1");
  await expect(page.locator('a[href="/goals"]').nth(1)).toContainText("64%");
});
