import { render, screen, waitFor } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { DashboardOverview } from "../components/mvp/dashboard-overview";
import { queueJsonResponses } from "./fetch-mock";

describe("DashboardOverview", () => {
  it("loads live dashboard counts from the API", async () => {
    queueJsonResponses([
      {
        body: [
          {
            id: "journal-1",
            title: "Journal entry",
            content: "Reflection",
            entryType: "journal",
            createdAt: "2026-03-08T08:00:00.000Z",
            updatedAt: "2026-03-08T08:00:00.000Z"
          },
          {
            id: "journal-2",
            title: "Second entry",
            content: "Further reflection",
            entryType: "journal",
            createdAt: "2026-03-08T09:00:00.000Z",
            updatedAt: "2026-03-08T09:00:00.000Z"
          }
        ]
      },
      {
        body: [
          {
            id: "diary-1",
            title: "Morning check-in",
            content: "Prompted entry",
            mood: "steady",
            entryDate: "2026-03-08",
            autoGenerated: false,
            createdAt: "2026-03-08T07:00:00.000Z",
            updatedAt: "2026-03-08T07:00:00.000Z"
          }
        ]
      },
      {
        body: [
          {
            id: "note-1",
            title: "Idea",
            content: "Connect memory to goals",
            category: "Ideas",
            tags: ["memory"],
            isPinned: true,
            updatedAt: "2026-03-08T06:00:00.000Z"
          },
          {
            id: "note-2",
            title: "Prompt",
            content: "Review mirror state",
            category: "Prompts",
            tags: [],
            isPinned: false,
            updatedAt: "2026-03-08T06:10:00.000Z"
          },
          {
            id: "note-3",
            title: "Action",
            content: "Ship UI tests",
            category: "Action",
            tags: ["tests"],
            isPinned: false,
            updatedAt: "2026-03-08T06:20:00.000Z"
          }
        ]
      },
      {
        body: {
          items: [],
          stats: {
            total: 2,
            active: 1,
            completed: 1,
            averageProgress: 55,
            completionRate: 50
          }
        }
      }
    ]);

    render(<DashboardOverview />);

    expect(screen.getByText("Dashboard-Zahlen werden geladen...")).toBeInTheDocument();

    await waitFor(() => {
      expect(screen.getByText("Dashboard zeigt Live-Zahlen aus der API.")).toBeInTheDocument();
    });

    expect(document.querySelector('a[href="/journal"]')).toHaveTextContent("2");
    expect(document.querySelector('a[href="/diary"]')).toHaveTextContent("1");
    expect(document.querySelector('a[href="/notes"]')).toHaveTextContent("3");
    expect(document.querySelector('a[href="/goals"]')).toHaveTextContent("55%");
  });

  it("surfaces API failures instead of hiding them", async () => {
    queueJsonResponses([
      {
        status: 500,
        body: {
          message: "Journal down."
        }
      },
      { body: [] },
      { body: [] },
      {
        body: {
          items: [],
          stats: {
            total: 0,
            active: 0,
            completed: 0,
            averageProgress: 0,
            completionRate: 0
          }
        }
      }
    ]);

    render(<DashboardOverview />);

    await waitFor(() => {
      expect(screen.getByText(/Journal down\./)).toBeInTheDocument();
    });
  });
});
