import { Inject, Injectable, NotFoundException, OnModuleInit, Optional } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { DiaryEntrySummary } from "@aion/shared-types";
import { LOCAL_USER_ID } from "../common/app-constants";
import { DesktopStateService } from "../common/desktop-state.service";
import { PRISMA_SERVICE } from "../common/prisma.tokens";
import type { PrismaService } from "../common/prisma.service";
import { AuditService } from "../audit/audit.service";
import { CreateDiaryEntryDto } from "./dto/create-diary-entry.dto";
import { UpdateDiaryEntryDto } from "./dto/update-diary-entry.dto";

interface DiaryPromptRecord {
  id: string;
  promptText: string;
  promptType: string;
}

interface DiaryEntryRecord extends DiaryEntrySummary {}

function createDefaultPrompts(): DiaryPromptRecord[] {
  return [
    {
      id: randomUUID(),
      promptType: "reflection",
      promptText: "Was war heute der ehrlichste Moment?"
    },
    {
      id: randomUUID(),
      promptType: "coherence",
      promptText: "Wo warst du heute koharent und wo nicht?"
    },
    {
      id: randomUUID(),
      promptType: "action",
      promptText: "Welcher kleine Schritt waere morgen wirklich echt?"
    }
  ];
}

function createDefaultEntries(): DiaryEntryRecord[] {
  const now = new Date().toISOString();

  return [
    {
      id: randomUUID(),
      title: "Tageszusammenfassung",
      content: "Heute war der Fokus klarer als gestern. Das System sollte daraus Wachstumsimpulse ableiten koennen.",
      mood: "focused",
      entryDate: now,
      autoGenerated: false,
      sourceContext: "manual",
      createdAt: now,
      updatedAt: now
    }
  ];
}

@Injectable()
export class DiaryService implements OnModuleInit {
  private prompts: DiaryPromptRecord[] = createDefaultPrompts();
  private entries: DiaryEntryRecord[] = createDefaultEntries();

  constructor(
    private readonly auditService: AuditService,
    @Optional() @Inject(PRISMA_SERVICE) private readonly prisma?: PrismaService,
    @Optional() private readonly desktopState?: DesktopStateService
  ) {}

  async onModuleInit() {
    if (!this.prisma) {
      if (this.desktopState?.isEnabled()) {
        this.prompts = await this.desktopState.loadSection("diary.prompts", this.prompts);
        this.entries = await this.desktopState.loadSection("diary.entries", this.entries);
      }
      return;
    }

    await this.prisma.ensureLocalUser();
    const [prompts, entries] = await Promise.all([
      this.prisma.diaryPrompt.findMany({ orderBy: { createdAt: "asc" } }),
      this.prisma.diaryEntry.findMany({
        where: { userId: LOCAL_USER_ID },
        orderBy: { createdAt: "desc" }
      })
    ]);

    if (prompts.length === 0) {
      await this.prisma.diaryPrompt.createMany({
        data: this.prompts.map((prompt) => ({
          id: prompt.id,
          promptText: prompt.promptText,
          promptType: prompt.promptType
        }))
      });
    } else {
      this.prompts = prompts.map((prompt) => ({
        id: prompt.id,
        promptText: prompt.promptText,
        promptType: prompt.promptType
      }));
    }

    if (entries.length === 0) {
      await this.prisma.diaryEntry.createMany({
        data: this.entries.map((entry) => ({
          id: entry.id,
          userId: LOCAL_USER_ID,
          title: entry.title,
          content: entry.content,
          mood: entry.mood,
          entryDate: new Date(entry.entryDate),
          autoGenerated: entry.autoGenerated,
          sourceContext: entry.sourceContext,
          createdAt: new Date(entry.createdAt),
          updatedAt: new Date(entry.updatedAt)
        }))
      });
    } else {
      this.entries = entries.map((entry) => ({
        id: entry.id,
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: entry.entryDate.toISOString(),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext ?? undefined,
        createdAt: entry.createdAt.toISOString(),
        updatedAt: entry.updatedAt.toISOString()
      }));
    }
  }

  private async persistCreate(entry: DiaryEntryRecord) {
    if (!this.prisma) {
      if (this.desktopState?.isEnabled()) {
        await this.desktopState.saveSection("diary.entries", this.entries);
      }
      return;
    }

    await this.prisma.diaryEntry.create({
      data: {
        id: entry.id,
        userId: LOCAL_USER_ID,
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: new Date(entry.entryDate),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext,
        createdAt: new Date(entry.createdAt),
        updatedAt: new Date(entry.updatedAt)
      }
    });
  }

  private async persistUpdate(entry: DiaryEntryRecord) {
    if (!this.prisma) {
      if (this.desktopState?.isEnabled()) {
        await this.desktopState.saveSection("diary.entries", this.entries);
      }
      return;
    }

    await this.prisma.diaryEntry.update({
      where: { id: entry.id },
      data: {
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: new Date(entry.entryDate),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext,
        updatedAt: new Date(entry.updatedAt)
      }
    });
  }

  private async persistDelete(id: string) {
    if (!this.prisma) {
      if (this.desktopState?.isEnabled()) {
        await this.desktopState.saveSection("diary.entries", this.entries);
      }
      return;
    }

    await this.prisma.diaryEntry.delete({
      where: { id }
    });
  }

  async listEntries(userId: string = LOCAL_USER_ID) {
    if (!this.prisma || userId === LOCAL_USER_ID) {
      return this.entries;
    }

    const entries = await this.prisma.diaryEntry.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" }
    });

    return entries.map((entry) => ({
      id: entry.id,
      title: entry.title,
      content: entry.content,
      mood: entry.mood,
      entryDate: entry.entryDate.toISOString(),
      autoGenerated: entry.autoGenerated,
      sourceContext: entry.sourceContext ?? undefined,
      createdAt: entry.createdAt.toISOString(),
      updatedAt: entry.updatedAt.toISOString()
    }));
  }

  async getEntry(id: string, userId: string = LOCAL_USER_ID) {
    if (this.prisma && userId !== LOCAL_USER_ID) {
      const entry = await this.prisma.diaryEntry.findFirst({
        where: { id, userId }
      });

      if (!entry) {
        throw new NotFoundException("Tagebucheintrag nicht gefunden.");
      }

      return {
        id: entry.id,
        title: entry.title,
        content: entry.content,
        mood: entry.mood,
        entryDate: entry.entryDate.toISOString(),
        autoGenerated: entry.autoGenerated,
        sourceContext: entry.sourceContext ?? undefined,
        createdAt: entry.createdAt.toISOString(),
        updatedAt: entry.updatedAt.toISOString()
      };
    }

    const entry = this.entries.find((item) => item.id === id);
    if (!entry) {
      throw new NotFoundException("Tagebucheintrag nicht gefunden.");
    }

    return entry;
  }

  getPrompts() {
    return this.prompts;
  }

  async createEntry(dto: CreateDiaryEntryDto, userId: string = LOCAL_USER_ID) {
    const now = new Date().toISOString();
    const entry: DiaryEntryRecord = {
      id: randomUUID(),
      createdAt: now,
      updatedAt: now,
      autoGenerated: dto.autoGenerated ?? false,
      sourceContext: dto.sourceContext,
      title: dto.title,
      content: dto.content,
      mood: dto.mood,
      entryDate: dto.entryDate
    };

    if (!this.prisma || userId === LOCAL_USER_ID) {
      this.entries.unshift(entry);
      await this.persistCreate(entry);
    } else {
      await this.prisma.diaryEntry.create({
        data: {
          id: entry.id,
          userId,
          title: entry.title,
          content: entry.content,
          mood: entry.mood,
          entryDate: new Date(entry.entryDate),
          autoGenerated: entry.autoGenerated,
          sourceContext: entry.sourceContext,
          createdAt: new Date(entry.createdAt),
          updatedAt: new Date(entry.updatedAt)
        }
      });
    }
    await this.auditService.record({
      category: "diary",
      action: "entry.created",
      resource: entry.id,
      actorType: "user",
      actorId: userId,
      detail: `Der Tagebucheintrag "${entry.title}" wurde angelegt.`
    });
    return entry;
  }

  async updateEntry(id: string, dto: UpdateDiaryEntryDto, userId: string = LOCAL_USER_ID) {
    if (this.prisma && userId !== LOCAL_USER_ID) {
      const current = await this.prisma.diaryEntry.findFirst({
        where: { id, userId }
      });

      if (!current) {
        throw new NotFoundException("Tagebucheintrag nicht gefunden.");
      }

      const updatedAt = new Date();
      await this.prisma.diaryEntry.update({
        where: { id: current.id },
        data: {
          title: dto.title ?? current.title,
          content: dto.content ?? current.content,
          mood: dto.mood ?? current.mood,
          entryDate: dto.entryDate ? new Date(dto.entryDate) : current.entryDate,
          autoGenerated: dto.autoGenerated ?? current.autoGenerated,
          sourceContext: dto.sourceContext ?? current.sourceContext,
          updatedAt
        }
      });

      const updated = {
        id: current.id,
        title: dto.title ?? current.title,
        content: dto.content ?? current.content,
        mood: dto.mood ?? current.mood,
        entryDate: (dto.entryDate ? new Date(dto.entryDate) : current.entryDate).toISOString(),
        autoGenerated: dto.autoGenerated ?? current.autoGenerated,
        sourceContext: dto.sourceContext ?? current.sourceContext ?? undefined,
        createdAt: current.createdAt.toISOString(),
        updatedAt: updatedAt.toISOString()
      };

      await this.auditService.record({
        category: "diary",
        action: "entry.updated",
        resource: updated.id,
        actorType: "user",
        actorId: userId,
        detail: `Der Tagebucheintrag "${updated.title}" wurde aktualisiert.`
      });
      return updated;
    }

    const entry = await this.getEntry(id, userId);
    Object.assign(entry, dto, { updatedAt: new Date().toISOString() });
    await this.persistUpdate(entry);
    await this.auditService.record({
      category: "diary",
      action: "entry.updated",
      resource: entry.id,
      actorType: "user",
      actorId: userId,
      detail: `Der Tagebucheintrag "${entry.title}" wurde aktualisiert.`
    });
    return entry;
  }

  async removeEntry(id: string, userId: string = LOCAL_USER_ID) {
    if (this.prisma && userId !== LOCAL_USER_ID) {
      const current = await this.prisma.diaryEntry.findFirst({
        where: { id, userId }
      });

      if (!current) {
        throw new NotFoundException("Tagebucheintrag nicht gefunden.");
      }

      await this.prisma.diaryEntry.delete({
        where: { id: current.id }
      });

      await this.auditService.record({
        category: "diary",
        action: "entry.removed",
        resource: current.id,
        actorType: "user",
        actorId: userId,
        detail: `Der Tagebucheintrag "${current.title}" wurde entfernt.`
      });

      return {
        id: current.id,
        title: current.title,
        content: current.content,
        mood: current.mood,
        entryDate: current.entryDate.toISOString(),
        autoGenerated: current.autoGenerated,
        sourceContext: current.sourceContext ?? undefined,
        createdAt: current.createdAt.toISOString(),
        updatedAt: current.updatedAt.toISOString()
      };
    }

    const index = this.entries.findIndex((item) => item.id === id);
    if (index === -1) {
      throw new NotFoundException("Tagebucheintrag nicht gefunden.");
    }

    const [removed] = this.entries.splice(index, 1);
    await this.persistDelete(id);
    await this.auditService.record({
      category: "diary",
      action: "entry.removed",
      resource: removed.id,
      actorType: "user",
      actorId: userId,
      detail: `Der Tagebucheintrag "${removed.title}" wurde entfernt.`
    });
    return removed;
  }

  async prepareDailySummary(userId: string = LOCAL_USER_ID) {
    const entries = await this.listEntries(userId);
    const latest = entries[0];
    return {
      generatedAt: new Date().toISOString(),
      promptSeed: this.prompts.map((prompt) => prompt.promptText),
      latestEntryTitle: latest?.title ?? null
    };
  }
}
