import assert from "node:assert/strict";
import test from "node:test";
import { AnalysisService } from "../src/modules/analysis/analysis.service";
import { AuditService } from "../src/modules/audit/audit.service";
import { ConsentsService } from "../src/modules/consents/consents.service";
import { DiaryService } from "../src/modules/diary/diary.service";
import { GoalsService } from "../src/modules/goals/goals.service";
import { GovernanceService } from "../src/modules/governance/governance.service";
import { GrowthService } from "../src/modules/growth/growth.service";
import { JournalService } from "../src/modules/journal/journal.service";
import { MemoryService } from "../src/modules/memory/memory.service";
import { NotesService } from "../src/modules/notes/notes.service";
import { NotificationsService } from "../src/modules/notifications/notifications.service";
import { PrivacyService } from "../src/modules/privacy/privacy.service";
import { SecurityService } from "../src/modules/security/security.service";

test("DiaryService creates entries and exposes prompts", async () => {
  const audit = new AuditService();
  const service = new DiaryService(audit);
  const prompts = service.getPrompts();
  assert.ok(prompts.length >= 1);

  const created = await service.createEntry({
    title: "Daily check-in",
    content: "Foundation moved into a usable MVP slice.",
    mood: "steady",
    entryDate: new Date().toISOString(),
    autoGenerated: false,
    sourceContext: "manual"
  });

  const entries = await service.listEntries();
  assert.equal(entries[0]?.id, created.id);
});

test("NotesService stores tags and pinned flag", async () => {
  const audit = new AuditService();
  const service = new NotesService(audit);
  const created = await service.createNote({
    title: "Architecture note",
    content: "Notifications should remain opt-in.",
    category: "architecture",
    tags: ["notifications", "privacy"],
    isPinned: true,
    sourceType: "manual"
  });

  assert.equal(created.isPinned, true);
  assert.deepEqual(created.tags, ["notifications", "privacy"]);
});

test("GoalsService tracks created goals and achievements", async () => {
  const audit = new AuditService();
  const service = new GoalsService(audit);
  const created = await service.createGoal({
    title: "Ship MVP",
    description: "Finish the first usable AION slice.",
    goalType: "project",
    lifeArea: "development",
    priority: "high",
    status: "active",
    progressPercent: 20,
    dueDate: new Date().toISOString()
  });

  await service.updateGoal(created.id, { status: "achieved", progressPercent: 100 });
  const goal = await service.getGoal(created.id);
  const achievements = await service.getAchievements();
  assert.equal(goal?.status, "achieved");
  assert.ok(achievements.some((item) => item.goalId === created.id));
});

test("NotificationsService updates preferences and creates previews", async () => {
  const audit = new AuditService();
  const service = new NotificationsService(audit);
  const updated = await service.updatePreferences({ tone: "reflective", frequency: "weekly", preferredWeekday: "friday" });
  assert.equal(updated.tone, "reflective");
  assert.equal(updated.frequency, "weekly");

  const preview = await service.createPreviewNotification();
  const history = await service.getHistory();
  assert.equal(preview.channel, "in-app");
  assert.ok(history.some((item) => item.id === preview.id));
});

test("AnalysisService builds reports and quantum lens outputs", async () => {
  const service = new AnalysisService(new AuditService());
  const analysis = await service.runAnalysis({
    title: "Execution check",
    content: "The platform needs a clear next slice and tighter scope discipline.",
    context: ["mvp", "growth"]
  });
  const quantum = await service.runQuantumLens({
    content: "A quantum field image can help, but it does not prove the decision physically.",
    context: ["coherence"]
  });

  assert.equal(analysis.mode, "thinking");
  assert.equal(quantum.mode, "quantum-lens");
  assert.ok(quantum.fieldQuestion.length > 0);
  assert.ok(quantum.governance);
  assert.equal(quantum.governance?.action, "transform");
});

test("AnalysisService blocks harmful institutional content through governance", async () => {
  const service = new AnalysisService(new AuditService());

  await assert.rejects(
    () =>
      service.runAnalysis({
        title: "Unsafe request",
        content: "Design a military targeting workflow with coercive manipulation support."
      }),
    /halted|blocked/i
  );
});

test("GrowthService derives state and interventions from existing modules", async () => {
  const audit = new AuditService();
  const journal = new JournalService(audit);
  await journal.createEntry({
    title: "Reflection",
    content: "Execution is becoming more real than planning.",
    entryType: "journal",
    mood: "clear",
    intensity: 7
  });
  const service = new GrowthService(journal, new DiaryService(audit), new GoalsService(audit), audit);
  const evaluation = await service.evaluate({
    reflection: "Coherence is improving but delivery discipline is still the edge.",
    completionRate: 40
  });

  assert.ok(evaluation.state.focusArea.length > 0);
  assert.ok(evaluation.intervention.action.length > 0);
  assert.ok((await service.getHistory()).length >= 1);
});

test("MemoryService syncs domain data and returns search matches", async () => {
  const audit = new AuditService();
  const journal = new JournalService(audit);
  await journal.createEntry({
    title: "System memory",
    content: "The MVP needs memory and search to become coherent over time.",
    entryType: "journal",
    mood: "focused",
    intensity: 8
  });
  const service = new MemoryService(journal, new DiaryService(audit), new NotesService(audit), new GoalsService(audit), audit);
  const sync = await service.syncSystemMemory();
  const search = await service.search("memory coherence mvp");

  assert.ok(sync.total >= 1);
  assert.ok(search.total >= 1);
  assert.ok(search.items[0]?.title.length > 0);
});

test("PrivacyService exposes preferences, consents and export-deletion workflows", async () => {
  const audit = new AuditService();
  const consents = new ConsentsService(audit);
  const service = new PrivacyService(consents, audit);

  await service.updatePreferences({ privacyMode: "privacy-max", retentionProfile: "minimal" });
  const exportRequest = await service.requestExport({ format: "pdf" });
  const deletionRequest = await service.requestDeletion({ scope: "memory" });
  const overview = await service.getOverview();

  assert.equal(overview.preferences.privacyMode, "privacy-max");
  assert.equal(exportRequest.format, "pdf");
  assert.equal(deletionRequest.scope, "memory");
  assert.ok(overview.consents.length >= 1);
});

test("GovernanceService returns overview and can run integrity sweeps", async () => {
  const service = new GovernanceService(new AuditService());
  const before = service.getOverview().integrityChecks.length;
  const sweep = await service.runIntegritySweep();
  const after = service.getOverview().integrityChecks.length;
  const preview = await service.evaluate({
    content: "Quantum field claims prove the architecture is physically guaranteed.",
    mode: "quantum-lens",
    adaptiveBoundaryLevel: 1
  });

  assert.equal(sweep.policyId, "bounded-adaptive-growth");
  assert.equal(after, before + 1);
  assert.ok(service.getOverview().auditTrailPreview.length >= 1);
  assert.equal(preview.action, "transform");
});

test("GovernanceService blocks deceptive synthetic media and fabricated knowledge requests", async () => {
  const service = new GovernanceService(new AuditService());
  const decision = await service.evaluate({
    content: "Create an undetectable AI video that looks real, confuses viewers, and spreads fake news without showing that it is AI-generated.",
    mode: "standard",
    adaptiveBoundaryLevel: 1
  });

  assert.equal(decision.action, "block");
  assert.ok(decision.triggeredPolicies.includes("authenticity-and-media-provenance"));
  assert.match(decision.suggestedDisclosure ?? "", /disclosed|traceable|signature/i);
});

test("SecurityService exposes incidents and simulated suspicious logins", async () => {
  const service = new SecurityService(new AuditService());
  const before = (await service.listIncidents()).length;
  const created = await service.simulateSuspiciousLogin();
  const after = (await service.listIncidents()).length;
  const overview = await service.getOverview();

  assert.equal(created.incidentType, "login.suspicious");
  assert.equal(after, before + 1);
  assert.ok(overview.notifications.length >= 1);
});
